/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.tec.aws;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;

@ExtendWith(SpringExtension.class)
@SpringBootTest(classes={App.class})
class AppTest {

    @Autowired
    App app;

    @Autowired
    ObjectMapper objectMapper;

    @Test
    void testConfig() {
        Assertions.assertNotNull(app);
        Assertions.assertNotNull(objectMapper);
    }
}
