version: "3.7"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack-full:latest
    hostname: localstack
    ports:
      - "4566:4566"
    environment:
      - DEFAULT_REGION=us-west-2
      # required but not directly used: iam,cloudformation,sts
      - SERVICES=apigateway,lambda,s3,sqs,secretsmanager,iam,cloudformation,sts
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=true
      #- LAMBDA_DOCKER_NETWORK=shared
      - HOSTNAME_EXTERNAL=localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      # DOCKER_CMD="sudo docker"
      # Use these if mounting from local drive in serverless.yml
      # - HOST_TMP_FOLDER=${PWD}/.localstack
      # - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - ../.data/localstack:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      # TODO
      #- ./bin:/docker-entrypoint-initaws.d
